site_name: The ANCHOR 
site_description: Your gateway into Big Fish's documentation

theme:
  name: material
  custom_dir: docs/overrides
  logo: assets/images/bfg-logo.png
  palette:
    primary: custom
  font:
    text: Montserrat
  features:
    - search.suggest

plugins:
  - search

extra_css:
  - stylesheets/extra.css

nav:
  - Home: index.md
  - About: about.md
