site_name: The ANCHOR MkDocs 
site_description: Your gateway into Big Fish's documentation

theme:
  name: material
  custom_dir: docs/overrides
  logo: assets/images/bfg-logo.png
  palette:
    primary: custom
  font:
    text: Montserrat
  features:
    - search.suggest
    - navigation.tabs

plugins:
  - search

extra_css:
  - stylesheets/extra.css

nav:
  - Home: index.md
  - Developer User Guide:
    - Welcome Developer!: static/dev_welcome.md
    - The Onboarding Process: static/dev_onboarding.md
    - Security & Privacy Standards: static/dev_security.md
  - Producer Handbook: static/prod_welcome.md
